# Generated by Django 3.2.16 on 2024-11-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='货物编码')),
                ('location_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='库位编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '入库上架记录',
                'verbose_name_plural': '入库上架记录',
            },
        ),
    ]
