# Generated by Django 3.2.16 on 2024-11-29 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pda', '0003_rename_stockinrecord_goodlocationrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodLocationRecord',
            new_name='StockInRecord',
        ),
        migrations.AlterModelOptions(
            name='stockinrecord',
            options={'verbose_name': '上架绑定货品库位记录', 'verbose_name_plural': '上架绑定货品库位记录'},
        ),
    ]
