# Generated by Django 3.2.16 on 2024-11-21 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='仓库名称')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='仓库编码')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='仓库地址')),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='所属公司')),
            ],
            options={
                'verbose_name': '仓库信息',
                'verbose_name_plural': '仓库信息',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='库位名称')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='库位编号')),
                ('parent_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ptl.location', verbose_name='父级库位')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptl.warehouse', verbose_name='所属仓库')),
            ],
            options={
                'verbose_name': '库位信息',
                'verbose_name_plural': '库位信息',
            },
        ),
    ]
