# Generated by Django 3.2.16 on 2024-11-22 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('section', '灯塔'), ('node', '标签')], max_length=50, null=True, verbose_name='标签类型')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='标签外部编码')),
                ('internal_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='标签内部ID')),
            ],
            options={
                'verbose_name': '标签信息',
                'verbose_name_plural': '标签信息',
            },
        ),
        migrations.AddField(
            model_name='location',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ptl.label', verbose_name='标签'),
        ),
    ]
