# Generated by Django 3.2.16 on 2024-11-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptl', '0003_auto_20241122_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockCheckOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, null=True, verbose_name='盘点工单编号')),
                ('warehouse_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='仓库编号')),
                ('is_complete', models.BooleanField(default=False, verbose_name='完成状态')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '盘点任务工单',
                'verbose_name_plural': '盘点任务工单',
            },
        ),
        migrations.CreateModel(
            name='StockInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, null=True, verbose_name='入库单编号')),
                ('warehouse_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='仓库编号')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='入库业务类型')),
                ('order_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='业务单据编号')),
                ('is_complete', models.BooleanField(default=False, verbose_name='入库完成状态')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '上架任务工单',
                'verbose_name_plural': '上架任务工单',
            },
        ),
        migrations.CreateModel(
            name='StockOutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=32, null=True, verbose_name='出库单编号')),
                ('warehouse_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='仓库编号')),
                ('type', models.CharField(blank=True, max_length=50, null=True, verbose_name='出库业务类型')),
                ('order_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='业务单据编号')),
                ('is_complete', models.BooleanField(default=False, verbose_name='出库完成状态')),
                ('is_void', models.BooleanField(default=False, verbose_name='作废状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '下架任务工单',
                'verbose_name_plural': '下架任务工单',
            },
        ),
        migrations.CreateModel(
            name='StockOutGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='货物编码')),
                ('goods_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='货物描述')),
                ('goods_qty', models.IntegerField(blank=True, null=True, verbose_name='货物数量')),
                ('is_complete', models.BooleanField(default=False, verbose_name='出货完成状态')),
                ('location_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='库位编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stock_out_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptl.stockoutorder', verbose_name='入库工单')),
            ],
            options={
                'verbose_name': '上架产品',
                'verbose_name_plural': '上架产品',
            },
        ),
        migrations.CreateModel(
            name='StockInGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='货物编码')),
                ('goods_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='货物描述')),
                ('goods_qty', models.IntegerField(blank=True, null=True, verbose_name='货物数量')),
                ('is_complete', models.BooleanField(default=False, verbose_name='入库完成状态')),
                ('location_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='库位编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stock_in_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptl.stockinorder', verbose_name='入库工单')),
            ],
            options={
                'verbose_name': '上架产品',
                'verbose_name_plural': '上架产品',
            },
        ),
        migrations.CreateModel(
            name='StockCheckGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='货物编码')),
                ('goods_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='货物描述')),
                ('goods_qty', models.IntegerField(blank=True, null=True, verbose_name='货物数量')),
                ('is_complete', models.BooleanField(default=False, verbose_name='盘点完成状态')),
                ('location_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='库位编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('stock_check_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptl.stockcheckorder', verbose_name='盘点任务')),
            ],
            options={
                'verbose_name': '盘点产品',
                'verbose_name_plural': '盘点产品',
            },
        ),
    ]
