# Generated by Django 3.2.16 on 2024-11-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptl', '0004_stockcheckgoods_stockcheckorder_stockingoods_stockinorder_stockoutgoods_stockoutorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinorder',
            name='warehouse_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='仓库名称'),
        ),
    ]
