# Generated by Django 3.2.16 on 2024-11-26 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptl', '0006_auto_20241126_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockingoods',
            options={'verbose_name': '上架货品', 'verbose_name_plural': '上架货品'},
        ),
        migrations.RenameField(
            model_name='stockoutgoods',
            old_name='goods_qty',
            new_name='plan_qty',
        ),
        migrations.RemoveField(
            model_name='stockingoods',
            name='goods_qty',
        ),
        migrations.AddField(
            model_name='stockcheckorder',
            name='order_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='业务单据编号'),
        ),
        migrations.AddField(
            model_name='stockcheckorder',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='盘点业务类型'),
        ),
        migrations.AddField(
            model_name='stockcheckorder',
            name='warehouse_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出货仓库'),
        ),
        migrations.AddField(
            model_name='stockingoods',
            name='actual_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='实际数量'),
        ),
        migrations.AddField(
            model_name='stockingoods',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='批次号'),
        ),
        migrations.AddField(
            model_name='stockingoods',
            name='plan_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='计划数量'),
        ),
        migrations.AddField(
            model_name='stockingoods',
            name='supplier_batch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='供应商批次号'),
        ),
        migrations.AddField(
            model_name='stockinorder',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='stockinorder',
            name='stock_staff',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='入库人员'),
        ),
        migrations.AddField(
            model_name='stockoutgoods',
            name='actual_qty',
            field=models.IntegerField(blank=True, null=True, verbose_name='实际数量'),
        ),
        migrations.AddField(
            model_name='stockoutgoods',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='批次号'),
        ),
        migrations.AddField(
            model_name='stockoutgoods',
            name='supplier_batch',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='供应商批次号'),
        ),
        migrations.AddField(
            model_name='stockoutorder',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='stockoutorder',
            name='stock_staff',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出库人员'),
        ),
        migrations.AlterField(
            model_name='stockingoods',
            name='stock_in_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptl.stockinorder', verbose_name='入库单号'),
        ),
        migrations.AlterField(
            model_name='stockoutgoods',
            name='stock_out_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ptl.stockoutorder', verbose_name='出库单号'),
        ),
        migrations.AlterField(
            model_name='stockoutorder',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='完成状态'),
        ),
        migrations.AlterField(
            model_name='stockoutorder',
            name='is_void',
            field=models.BooleanField(default=False, verbose_name='是否作废'),
        ),
        migrations.AlterField(
            model_name='stockoutorder',
            name='number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='出库单号'),
        ),
        migrations.AlterField(
            model_name='stockoutorder',
            name='order_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='来源单号'),
        ),
        migrations.AlterField(
            model_name='stockoutorder',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='出库类型'),
        ),
    ]
