# Generated by Django 3.2.16 on 2024-11-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptl', '0007_auto_20241126_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockCheckGoods',
        ),
        migrations.DeleteModel(
            name='StockCheckOrder',
        ),
    ]
